kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 9200  # Elasticsearch
        hostPort: 9200
      - containerPort: 5601  # Kibana
        hostPort: 5601
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
            "service-node-port-range": "80-32767"
